### PR TITLE
Add stumpy v1.9.2

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Popularity:  30630 downloads -  stumpy  1.9.2  STUMPY is a powerful and scalable Python library that computes something called a matrix profile, which can then be used for a variety of time series data mining tasks
  license: BSD-3-Clause
Release date:  Jul 28, 2021
Bug Tracker: new open issues https://github.com/TDAmeritrade/stumpy/issues
Github releases:  https://github.com/TDAmeritrade/stumpy/releases
Upstream Changelog: https://github.com/TDAmeritrade/stumpy/blob/main/CHANGELOG.md
Upstream license: https://github.com/TDAmeritrade/stumpy/blob/main/LICENSE.txt
Requirements from conda-forge: https://github.com/conda-forge/stumpy-feedstock/blob/master/recipe/meta.yaml
Upstream setup file: https://github.com/TDAmeritrade/stumpy/blob/v1.9.2/setup.py

Actions:
1. Change build number to `0`.
2. Add missing package `wheel`
3. Add `pip check`
4. Remove `setuptools `from the test/requires section

Result:
- all-succeeded

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
it failed on `s390x` because of an error:
```
conda.exceptions.ResolvePackageNotFound:
  - numba[version='>=0.48']
```

**Review by katietz — CHANGES_REQUESTED** [review]
You should add a skip for s390x with comment that it is disabled as numba is not available.

**Comment by skupr-anaconda** [comment]
> You should add a skip for s390x with comment that it is disabled as numba is not available.

DONE

**Review by katietz — APPROVED** [review]
Thanks!

**Pull request merged**
